### ISSUE TITLE
encryption error 

### ISSUE THREAD

**Issue by Mohsin2305** [arshadpatel2001/File-Encryption-Using-Hybrid-Cryptography#3]
after encryption of any file the size of ars file is 0kb

**Comment by arshadpatel2001** [comment]
I just checked it, the encryption seems to work well with .png files. What type of file were you trying encrypt?

**Comment by arshadpatel2001** [comment]
I just checked it, the encryption seems to work well with .png files. What type of file were you trying to encrypt?
